# SETUP INSTRUCTIONS
## assign unique-encounters_path to the path of the unique encounters file

# SLURM CONFIGURATION
num_processes: "7"
processor_assignment: "1"
# PIPELINE INSTRUCTIONS
make_pickle: "yes" # yes: make pickle files, no: do not make pickle files
make_dictionary: "yes" # yes: make dictionary files, no: do not make dictionary files
# FILE PATHS
data_path: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW"
groupings_path: "/cwork/jfr29/Sepy/groupings"
pickle_output_path: "/cwork/jfr29/Sepy/pickle/"
dictionary_output_path: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_Supertables/"
bed_unit_csv_fname:  "/cwork/jfr29/Sepy/AdditionalInformation/bed_units_to_icu_AH.csv"
variable_bounds_csv_fname : "/cwork/jfr29/Sepy/AdditionalInformation/Variable_Chart.csv"
dialysis_info_csn_fname: "/cwork/jfr29/Sepy/AdditionalInformation/PEACH_HD_CRRT.csv"
unique_encounters_path: 
  2014: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW/2014/encounter_2014_decomp_03112020.dsv"
  2015: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW/2015/encounter_2015_decomp_03112020.dsv"
  2016: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW/2016/encounter_2016_decomp_03112020.dsv"
  2017: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW/2017/encounter_2017_decomp_03112020.dsv"
  2018: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW/2018/encounter_2018_decomp_03112020.dsv"
  2020: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW/2020/encounter_2020_decomp_07222020.dsv"
  2021: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW/2021/encounter_2021_decomp_05032022.dsv"
  2022: "/hpc/group/kamaleswaranlab/GradyDataset/EMR_RAW/2022/encounter_2022_decomp_11082022.dsv"
dataset_identifier: "gr_y"
years_to_scrape_data: ["2014", "2015", "2016", "2017", "2018", "2020", "2021", "2022"]
# CSN FILTERING
encounter_type: "Inpatient" # "Inpatient", "Emergency", "all": all encounter types
age: "adult" # "adult": age >= 18, "pediatric": age < 18, "all": all ages
unique_enc_filter: "no" # "yes": only unique encounters, "no": all encounters
unique_enc:
  # - CSN1
  # - CSN2
  # - CSN3
# DICTIONARY PATH KEWORDS
dictionary_paths:
  comorbidity_types:
    - "ICD9_ahrq"
    - "ICD9_elix"
    - "ICD9_quan_deyo"
    - "ICD9_quan_elix"
    - "ICD9_single_ccs"
    - "ICD10_ahrq"
    - "ICD10_elix"
    - "ICD10_quan_deyo"
    - "ICD10_quan_elix"
    - "ICD10_single_ccs"
  grouping_types:
    - "gr_all_infusion_meds"
    - "gr_grouping_labs"
    - "gr_bed_labels"
  year_types:
    - ["INFUSIONMEDS", "infusion_meds"]
    - ["LABS", "lab"]
    - ["VITALS", "vitals"]
    - ["VENT", vent]
    - ["DEMOGRAPHICS", "demographics"]
    - ["GCS", "gcs"]
    - ["ENCOUNTER", "encounter"]
    - ["CULTURES", "cultures"]
    - ["BEDLOCATION", "bed_location"]
    - ["ORPROCEDURES", "or_procedures"]
    - ["DIAGNOSIS", "diagnoses"]
# YEARLY INSTANCE FUNCTIONS AND PARAMETERS
yearly_instance:
  import_labs:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    group_cols:
      - "physionet"
      - "import"
      - "super_table_col_name"
      - "component_id"
    date_cols:
      - "collection_time"
      - "lab_result_time"
    index_col: ["csn"]
    numeric_cols: null
  import_bed_locations:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    index_col: ["csn"]
    date_cols:
      - "bed_location_start"
      - "bed_location_end"
  import_demographics:
    drop_cols: ["study_id"]
    index_col: ["pat_id"]
    date_cols: [] # removed 'dob'
  import_infusion_meds:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    numeric_cols: []
    anti_infective_group_name: "anti-infective"
    vasopressor_group_name: "vasopressor"
    index_col: ["csn"]
    date_cols:
      - "med_order_time"
      - "med_action_time"
      - "med_start"
      - "med_stop"
  import_encounters:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    index_col: ["csn"]
    date_cols:
      - "ed_presentation_time"
      - "hospital_admission_date_time"
      - "hospital_discharge_date_time"
  import_vitals:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    index_col: ["csn"]
    date_cols: ["recorded_time"]
    merge_cols: [["end_tidal_co2_1", "end_tidal_co2_2", "end_tidal_co2"]]
  import_vent:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    index_col: ["csn"]
    numeric_cols:
      - "vent_rate_set"
      - "vent_tidal_rate_set"
      - "vent_tidal_rate_exhaled"
      - "peep"
      - "fio2"
    date_cols:
      - "recorded_time"
      - "vent_start_time"
      - "vent_stop_time"
      - "recorded_time"
  import_gcs:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    index_col: ["csn"]
    numeric_col:
      - "gcs_eye_score"
      - "gcs_verbal_score"
      - "gcs_motor_score"
      - "gcs_total_score"
    date_cols: ["recorded_time"]
  import_cultures:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    index_col: ["csn"]
    date_cols:
      - "specimen_collect_time"
      - "order_time"
      - "lab_result_time"
  import_procedures:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    index_col: ["csn"]
    date_cols:
      - "surgery_date"
      - "in_or_dttm"
      - "procedure_start_dttm"
      - "procedure_comp_dttm"
      - "out_or_dttm"
  import_diagnosis:
    drop_cols:
      - "study_id"
      - "har"
      - "mrn"
    index_col: ["csn"]
    date_cols: ["dx_time_date"]
# COMORBIDITY SUMMARY KEYWORDS
comorbidity_summary:
  - "ICD10_quan_deyo"
  - "ICD10_quan_elix"
  # - "ICD9_ahrq"
  # - "ICD9_elix"
  # - "ICD9_quan_deyo"
  # - "ICD9_quan_elix"
  # - "ICD9_single_ccs"
  # - "ICD10_ahrq"
  # - "ICD10_elix"
  # - "ICD10_single_ccs"
# SEPSIS SUMMARY DIRECTORY PATHES
sepsis_summary: "gr_sepsis_summary"
sepsis_summary_types:
  - "sofa_summary"
  - "sep3_summary"
  - "sirs_summary"
  - "sep2_summary"
  - "encounter_summary"
  - "error_summary"
  # - "ahrq_ICD10_summary"
  # - "elix_ICD10_summary"
  - "quan_deyo_ICD10_summary"
  - "quan_elix_ICD10_summary"
  # - "ccs_ICD10_summary"